"""Regenerate sql/schema.sql from src/database/models.py (the source of truth)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from src.database.models import metadata  # noqa: E402
from src.database.repository import LATEST_VIEWS  # noqa: E402

out = ["-- Generated by scripts/export_schema.py from src/database/models.py. Do not edit by hand.",
       "-- All monetary values are ₹ crore. Tables are append-only; v_*_latest views resolve current values.", ""]
for t in metadata.sorted_tables:
    out.append(str(CreateTable(t).compile(dialect=postgresql.dialect())).strip() + ";\n")
    for ix in t.indexes:
        out.append(str(CreateIndex(ix).compile(dialect=postgresql.dialect())).strip() + ";\n")
out += [v.strip() + ";\n" for v in LATEST_VIEWS]
(Path(__file__).resolve().parents[1] / "sql" / "schema.sql").write_text("\n".join(out), encoding="utf-8")
print("sql/schema.sql written")
