-- Generated by scripts/export_schema.py from src/database/models.py. Do not edit by hand.
-- All monetary values are ₹ crore. Tables are append-only; v_*_latest views resolve current values.

CREATE TABLE companies (
	company_id SERIAL NOT NULL, 
	company_name VARCHAR(255) NOT NULL, 
	ticker VARCHAR(32) NOT NULL, 
	isin VARCHAR(16), 
	exchange VARCHAR(8) DEFAULT 'NSE' NOT NULL, 
	sector VARCHAR(64), 
	industry VARCHAR(128), 
	market_cap FLOAT, 
	listing_status VARCHAR(16) DEFAULT 'Listed', 
	fiscal_year_end_month INTEGER DEFAULT '3', 
	source VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	PRIMARY KEY (company_id), 
	UNIQUE (ticker)
);

CREATE TABLE pipeline_runs (
	run_id SERIAL NOT NULL, 
	job VARCHAR(64) NOT NULL, 
	source VARCHAR(64), 
	started_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	finished_at TIMESTAMP WITHOUT TIME ZONE, 
	status VARCHAR(16), 
	n_ok INTEGER, 
	n_failed INTEGER, 
	message TEXT, 
	PRIMARY KEY (run_id)
);

CREATE TABLE ai_outputs (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	model VARCHAR(64), 
	fact_pack JSON, 
	output TEXT, 
	unverified_numbers JSON, 
	PRIMARY KEY (id), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE TABLE calculated_metrics (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	fiscal_year INTEGER NOT NULL, 
	calc_run_id INTEGER NOT NULL, 
	revenue_growth FLOAT, 
	revenue_cagr_3y FLOAT, 
	revenue_cagr_5y FLOAT, 
	ebitda_growth FLOAT, 
	ebitda_cagr_3y FLOAT, 
	eps_cagr_3y FLOAT, 
	ebitda_margin FLOAT, 
	ebit_margin FLOAT, 
	pat_margin FLOAT, 
	roic FLOAT, 
	roe FLOAT, 
	fcf_margin FLOAT, 
	fcf_conversion FLOAT, 
	ocf_to_ebitda FLOAT, 
	net_debt FLOAT, 
	net_debt_to_ebitda FLOAT, 
	interest_coverage FLOAT, 
	debt_to_equity FLOAT, 
	fcf_to_debt FLOAT, 
	dso FLOAT, 
	dio FLOAT, 
	dpo FLOAT, 
	cash_conversion_cycle FLOAT, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_metric_run UNIQUE (company_id, fiscal_year, calc_run_id), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE INDEX ix_calculated_metrics_company_id ON calculated_metrics (company_id);

CREATE TABLE data_issues (
	id SERIAL NOT NULL, 
	run_id INTEGER, 
	company_id INTEGER, 
	fiscal_year INTEGER, 
	check_name VARCHAR(64) NOT NULL, 
	severity VARCHAR(8) NOT NULL, 
	detail TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(run_id) REFERENCES pipeline_runs (run_id), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE TABLE deal_pipeline (
	company_id INTEGER NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	thesis TEXT, 
	concerns TEXT, 
	next_steps TEXT, 
	notes TEXT, 
	added_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	PRIMARY KEY (company_id), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE TABLE financials (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	fiscal_year INTEGER NOT NULL, 
	period_end DATE NOT NULL, 
	filing_date DATE NOT NULL, 
	filing_date_estimated BOOLEAN DEFAULT 'true' NOT NULL, 
	revenue FLOAT, 
	cost_of_revenue FLOAT, 
	ebitda FLOAT, 
	ebit FLOAT, 
	depreciation FLOAT, 
	pretax_income FLOAT, 
	tax_expense FLOAT, 
	pat FLOAT, 
	eps FLOAT, 
	operating_cash_flow FLOAT, 
	capex FLOAT, 
	free_cash_flow FLOAT, 
	total_assets FLOAT, 
	total_equity FLOAT, 
	total_debt FLOAT, 
	cash FLOAT, 
	receivables FLOAT, 
	inventory FLOAT, 
	payables FLOAT, 
	interest_expense FLOAT, 
	dividends_paid FLOAT, 
	source VARCHAR(64) NOT NULL, 
	ingested_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_fin_version UNIQUE (company_id, fiscal_year, source, ingested_at), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE INDEX ix_financials_company_id ON financials (company_id);

CREATE TABLE market_data (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	date DATE NOT NULL, 
	share_price FLOAT, 
	shares_outstanding_cr FLOAT, 
	market_cap FLOAT, 
	enterprise_value FLOAT, 
	source VARCHAR(64) NOT NULL, 
	ingested_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_market_obs UNIQUE (company_id, date, source), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE INDEX ix_market_data_company_id ON market_data (company_id);

CREATE TABLE ownership (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	date DATE NOT NULL, 
	promoter_holding FLOAT, 
	institutional_holding FLOAT, 
	public_holding FLOAT, 
	source VARCHAR(64) NOT NULL, 
	ingested_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_own_obs UNIQUE (company_id, date, source), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE INDEX ix_ownership_company_id ON ownership (company_id);

CREATE TABLE pipeline_history (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	changed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), 
	note TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE TABLE screening_results (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	screening_date DATE NOT NULL, 
	growth_score FLOAT, 
	profitability_score FLOAT, 
	cash_flow_score FLOAT, 
	leverage_score FLOAT, 
	valuation_score FLOAT, 
	working_capital_score FLOAT, 
	total_score FLOAT, 
	archetype VARCHAR(64), 
	data_quality VARCHAR(8), 
	passes_screen BOOLEAN, 
	weights JSON, 
	calc_run_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE INDEX ix_screening_results_company_id ON screening_results (company_id);

CREATE TABLE valuation (
	id SERIAL NOT NULL, 
	company_id INTEGER NOT NULL, 
	date DATE NOT NULL, 
	ev_ebitda FLOAT, 
	ev_sales FLOAT, 
	pe FLOAT, 
	fcf_yield FLOAT, 
	peer_group VARCHAR(128), 
	peer_median_ev_ebitda FLOAT, 
	calc_run_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id)
);

CREATE INDEX ix_valuation_company_id ON valuation (company_id);

DROP VIEW IF EXISTS v_financials_latest;

CREATE VIEW v_financials_latest AS
       SELECT * FROM (
         SELECT f.*, ROW_NUMBER() OVER (PARTITION BY company_id, fiscal_year ORDER BY ingested_at DESC, id DESC) AS rn
         FROM financials f) t WHERE rn = 1;

DROP VIEW IF EXISTS v_market_latest;

CREATE VIEW v_market_latest AS
       SELECT * FROM (
         SELECT md.*, ROW_NUMBER() OVER (PARTITION BY company_id ORDER BY date DESC, ingested_at DESC) AS rn
         FROM market_data md) t WHERE rn = 1;

DROP VIEW IF EXISTS v_ownership_latest;

CREATE VIEW v_ownership_latest AS
       SELECT * FROM (
         SELECT o.*, ROW_NUMBER() OVER (PARTITION BY company_id ORDER BY date DESC, ingested_at DESC) AS rn
         FROM ownership o) t WHERE rn = 1;
